OpenAMP/libmetal

lib/system/freertos/irq.c
lib/system/generic/irq.c

Clean up list usage in the IRQ handling of generic system
and FreeRTPS system.

irq: list usage cleanup in IRQ handling

---

.gitignore

gitignore: Update to ignore vim temp files

---

lib/mutex.h
lib/system/freertos/mutex.h
lib/system/generic/mutex.h
lib/system/linux/mutex.h
lib/system/zephyr/mutex.h
test/system/freertos/mutex.c
test/system/generic/mutex.c
test/system/linux/condition.c
test/system/linux/mutex.c
test/system/zephyr/mutex.c

A few changes related mutexes that cleanup some init, inlining, and zephyr support.

Mutex update/cleanups

---

lib/system/freertos/init.c
lib/system/freertos/irq.c
lib/system/generic/init.c
lib/system/generic/irq.c

Cleanup FreeRTOS & generic irq init to match what we did in Zephyr.

Irq cleanup other

---

lib/cache.h
lib/io.c
lib/io.h
lib/processor/microblaze/cpu.h

This patch set is a fix of compilation issue faced using IAR IDE for cortex M.
-  return for void function
- void pointer incrementation
- default implementation of the 64 bit atomic access for 32 bit arm core

fix miscellaneous compilation issue

---

lib/compiler/gcc/compiler.h
lib/compiler/iar/compiler.h

Change-Id: I9d87ca5ea95ced0d81c186fb08adc81c69755ce9

compiler.h: add METAL_PACKED_BEGIN and METAL_PACKED_END

---

lib/system/nuttx/io.c

Change-Id: I809472bfecfe18179d4a3ace47c26fe0baa2e771

nuttx: handle the no zero virtual address correctly

---

lib/device.c
lib/processor/ceva/cpu.h

Fix build error for CEVA 1643 DSP

---

lib/device.c
lib/shmem.c

This series proposes corrections for few compilation issues and issues reported by IAR c-stat tools (alignment with MISRA C 2012)
As the code is platform dependent , i fixed only the the common part.

 IAR c-stat reports

---

lib/processor/x86/CMakeLists.txt
lib/processor/x86/atomic.h
lib/processor/x86/cpu.h

lib: processor: add x86 support

---

MAINTAINERS.md

Add Arnaud and Ed as project maintainers
Add Ed as Xilinx platforms maintainer

 Maintainers: update project maintainers

---

.github/workflows/continuous-integration.yml

Create a first series of tests for continuous integration
- non regression tests for Linux system
- run generic checkpatch action 

Create CI tests using github workflow

---

.github/workflows/compliance.yml
scripts/ci/check_compliance.py

The webispy/checkpatch-action does not seem to work properly.
Even if it detects coding style issue, the return status is successful.
This patch replaces the action by the compliance python script obtained
from the Zephyr project.
This script also runs gitlint to check commit messages.
Notice that this PR depends on https://github.com/OpenAMP/libmetal/pull/131 
Only last commit named CI: "rework compliance test" as to be reviewed
The PR will we rebased when https://github.com/OpenAMP/libmetal/pull/131  will be integrated
Signed-off-by: Arnaud Pouliquen arnaud.pouliquen@st.com

CI: rework compliance test

---

CMakeLists.txt

Signed-off-by: Ed Mooring <ed.mooring@xilinx.com>

Set CMake minimum version to 3.0.2

---

test/system/zephyr/main.c

Since Zephyr2.4.0 the k_mem_pool is deprecated and replaced by k_heap

fix Zephyr CI test

---

lib/atomic.h
lib/compiler.h
lib/compiler/CMakeLists.txt
lib/compiler/armcc/CMakeLists.txt
lib/compiler/armcc/errno.h
lib/errno.h

add support of the ARMCC compiler:
- impose the use of the GNU extension
- add missing errno define

ARMCC compiler support

---

.github/workflows/compliance.yml

Cherry-pick of fixed already applied in openamp lib (https://github.com/OpenAMP/open-amp/pull/277)

Ci test fixes

---

MAINTAINERS.md

Update Ed Mooring's email address and remove the machine specific
entries.
Signed-off-by: Ed Mooring <ed.mooring@gmail.com>

MAINTAINERS: update maintainer email address.

---

.github/actions/build_ci/entrypoint.sh

Update zephyr SDK to 0.15.0 to fix CI build issue. Align related code with the open-amp CI.

CI: Fix Zephyr build by updating Zephyr SDK version to 0.15.0

---

lib/init.c
lib/sys.h

to allow to invoke metal_init and metal_finish multiple times

Add reference count to metal_common_state

---

.github/workflows/stales.yml

Add action to add stale label on issues and PR when no activity during 45 days.

github action: add stales action

---

README.md
cmake/syscheck.cmake

Small changes for the latest Zephyr.

Zephyr updates
