OpenAMP/libmetal

lib/log.h

fix c++ invalid conversion error in metal_log() definition.

log: fix c++ invalid conversion compilation error

---

lib/system/freertos/zynq7/sys.c
lib/system/freertos/zynqmp_a53/sys.c
lib/system/freertos/zynqmp_r5/sys.c
lib/system/generic/zynq7/sys.c
lib/system/generic/zynqmp_a53/sys.c
lib/system/generic/zynqmp_r5/sys.c

Fix issue that caused interrupts to not been disabled.
When cpsr.if was 0 and old value was 0, interrupt were not disabled.
This would happen if interrupt were initially enabled, after disabling, enabling and disabling again.
Changed sys_irq_save_disable() to read cpsr and compare interrupt bits to their disabled state, making sure interrupts gets disabled if different.

Fix sys irq save disable

---

lib/io.h

When page_shift is larger than the number of bits of the offset
type, the offset shift operation will be undefined.
This fix detects if the page_shift is too big, if yes, the page
index will be "0".

io: fix page_shift too big issue

---

lib/compiler/gcc/compiler.h

The define of restrict was inside the c++ extern define block.  This
causes issues on older toolchains.

compiler: Fix restrict definition

---

.travis.yml

Compile Zephyr instead of Linux in the Zephyr CI build.

ci: fix Zephyr CI compilation

---

cmake/platforms/template-generic.cmake
lib/system/generic/template/CMakeLists.txt
lib/system/generic/template/sys.c
lib/system/generic/template/sys.h

Add a template example for a generic platform to show what code needs to
get implemented by someone doing a port.  This also allows us to test
build the generic platform without any significant external
dependancies.

generic: Add a template files as starting point for a port

---

cmake/platforms/template-freertos.cmake
lib/system/freertos/template/CMakeLists.txt
lib/system/freertos/template/sys.c
lib/system/freertos/template/sys.h

Add a template example for a FreeRTOS platform to show what code needs
to get implemented by someone doing a port.  This also allows us to
test build the FreeRTOS platform without any significant external
dependancies.

freertos: Add a template files as starting point for a port

---

lib/system/zephyr/alloc.c
lib/system/zephyr/alloc.h
lib/system/zephyr/cache.c
lib/system/zephyr/condition.c
lib/system/zephyr/condition.h
lib/system/zephyr/cortexm/sys.c
lib/system/zephyr/cortexm/sys.h
lib/system/zephyr/device.c
lib/system/zephyr/init.c
lib/system/zephyr/io.c
lib/system/zephyr/io.h
lib/system/zephyr/irq.c
lib/system/zephyr/irq.h
lib/system/zephyr/mutex.h
lib/system/zephyr/shmem.c
lib/system/zephyr/sleep.c
lib/system/zephyr/sys.h
lib/system/zephyr/time.c
test/system/zephyr/metal-test-internal.h

Put Linaro to the license text in the files of libmetal
Zephyr implementation.

Fix license text for files in lib/system/zephyr

---

.travis.yml

Build with tests enabled for Zephyr in CI.

ci: zephyr: enable to build with tests

---

cmake/depends.cmake

Add an if (WITH_DOCS) wrapper around find_package(Doxygen).  We only
need Doxygen if we are trying to build the docs.

cmake: Only look for doxygen package if docs enabled

---

lib/compiler.h
lib/compiler/CMakeLists.txt
lib/compiler/iar/CMakeLists.txt
lib/compiler/iar/compiler.h

Add IAR support in compiler.h. Add associated iar folder.

compiler: add IAR compiler file

---

lib/CMakeLists.txt

When trying to build libmetal as a library with Zephyr we should use
zephyr_library_sources instead of target_sources.  This issue shows up
because of a fix in Zephyr post the 1.12.0 release.

cmake: Fix Zephyr library integration

---

.travis.yml

Zephyr has deprecated the environment variable ZEPHYR_GCC_VARIANT and
replaced it with ZEPHYR_TOOLCHAIN_VARIANT.  Match this change.

ci: Zephyr env var for toolchain

---

lib/system/freertos/mutex.h

As freertos does not seem to provide way to statically initialize semaphore,
use atomic int which provides this functionality.
changes: added metal/atomic.h 
Signed-off-by: Ben Levinsky <ben.levinsky@xilinx.com>

lib: system: freertos: mutex: change to use atomic_int instead of freertos construct V3

---

lib/system/linux/device.c

The Linux UIO dmem driver allows the dma memory allocation for clients.
Add the support for the UIO dmem driver.
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>

linux: device: Add the uio_dmem_genirq driver

---

lib/system/freertos/zynqmp_a53/sys.c
lib/system/generic/zynqmp_a53/sys.c

Fix incorrect test in if statement by replacing bitwise AND
with logical AND operation.
Found using Coccinelle.
Semantic Patch Language (SmPL) used:
<smpl>
@@
expression E1, E2;
@@
- !E1 & !E2
+ !E1 && !E2
</smpl>
Signed-off-by: Himanshu Jha <himanshujha199640@gmail.com>

zynqmp_a53: Convert '&' to '&&' operator in if statement

---

lib/atomic.h

Use cpp atomic if it is compiled for cpp application

Use cpp atomic if it is compiled for cpp application

---

lib/system/freertos/xlnx_common/irq.c

Add missing function pointer value to the IRQ controller
declaration.
Signed-off-by: Wendy Liang <wendy.liang@xilinx.com>

freertos: xlnx_common: fix irq controller declare

---

lib/system/freertos/xlnx_common/irq.c
lib/system/freertos/xlnx_common/sys.h
lib/system/generic/xlnx_common/irq.c
lib/system/generic/xlnx_common/sys.h

Change the type of the input argument of the Xilinx
common isr to (void *) to meet the Xilinx library
requirement.
Signed-off-by: Wendy Liang <wendy.liang@xilinx.com>

xlnx_common: change common isr input arg type

---

lib/utilities.h

since no all compiler support __builtin_assume_aligned
This reverts commit 0b979d4cbc9c51044664340539d66862597f3172.
Change-Id: I7c3523b63331917f3a330e08ba4196e1f1534daf

Revert "utilities: restrict the bitmap pointer is aligned"

---

examples/system/generic/zynqmp_r5/CMakeLists.txt
lib/atomic.h
lib/softirq.c
lib/spinlock.h
lib/system/generic/condition.c
lib/system/generic/condition.h
lib/system/linux/condition.c
lib/system/linux/condition.h
lib/system/zephyr/condition.c
lib/system/zephyr/condition.h
test/system/generic/zynqmp_r5/CMakeLists.txt

These patches fix the places which do not comply with the c11 atomic operations specification.

Fix atomic operations compilation errors

---

lib/softirq.c

Use atomic load to check if IRQ is enabled. For some compiler,
It is not allow to directly compare atomic type variable with
variables of other types.
Signed-off-by: Wendy Liang <wendy.liang@xilinx.com>

softirq: use atomic load to check if irq is enabled.

---

lib/system/zephyr/irq.c

metal_irq_save_disable and metal_irq_restore_enable to utilize the
Zephyr irq_lock & irq_unlock function.  While we don't have libmetal IRQ
support for Zephyr, using irq_lock/irq_unlock makes the most sense for
now and fixes build warnings since there aren't any implementations of
sys_irq_save_disable/sys_irq_restore_enable for Zephyr builds.

irq: zephyr: Restore implementations of metal_irq functions

---

examples/system/linux/zynqmp/zynqmp_amp_demo/shmem_throughput_demo.c

Inclusion of error.h in example shmem_throughput_demo.c leads to
build failure when using musl instead of glibc as C library.
The file does not use any error.h specific functions, only the
error codes which are defined in errno.h. So the include can be
changed to errno.h.
Signed-off-by: Joerg Hofrichter <joerg.hofrichter@ni.com>

examples: fixed include to make libmetal compile with TCLIBC=musl

---

lib/atomic.h

Reverts OpenAMP/libmetal#75  as it caused problems compiling with C++ as mentioned in issue #97.

Revert "Use cpp atomic if it is compiled for cpp application"

---

lib/system/linux/device.c

Closes the file descriptor which is opened when reading Linux device
properties. This prevents a file descriptor leak.
Signed-off-by: Toni Jones <toni.jones@ni.com>

linux: device: close device property fd

---

lib/system/nuttx/irq.c

nuttx: correctly handle the hardware which hasn't the interrupt controller

---

test/system/linux/shmem.c

During test we try to lock more memory than the limit
permitted.
This results in following traces:
metal: warning: failed to mlock shmem - Cannot allocate memory
metal: error: pagemap page not present, 3fd7560fd0 -> 80000000000000
metal: error: pagemap page not present, 3fd7560fd8 -> 80000000000000
metal: error: pagemap page not present, 3fd7560fe0 -> 80000000000000
metal: error: pagemap page not present, 3fd7560fe8 -> 80000000000000
[...]
This patch decreases the size of the shem to avoid to reach the limit

test: fix mlock allocation fail

---

MAINTAINERS.md

Change to the new mailing list and remove Wendy as a maintainer.

Change the mailing list to point the OpenAMP Project list.

---

lib/system/nuttx/irq.c

since the upstream remove sched_kfree and put the similar logic into kmm_free

nuttx: change sched_kfree to kmm_free

---

lib/compiler/gcc/atomic.h

Fix compilation issue for condition.c:
atomic_uintptr_t is not declared.
This occurs when the gcc compiler atomic lib is not used.

system: Linux: add missing atomic atomic_uintptr_t declaration

---

.gitlint
scripts/gitlint/commit_rules.py

Add gitlint configuration to allow contributor to check its
commit message compliance before sending its pull request.
The configuration files has been copied from Zephyr project.

gitlint: add giltlint configuration files

---

CMakeLists.txt

This commit introduces CMP0077 and set the policy to new behavior
and thus removes the following warning when using newer CMake versions:
```
Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
--help-policy CMP0077" for policy details.  Use the cmake_policy command
to set the policy and suppress this warning.`
```
Both OLD and NEW behavior will use the value defined earlier in the
CMake process, however the OLD behavior will also add an entry to the
CMakeCache.txt but ignore that value on sub-sequent invocations.
As this may lead to confusion on users looking into the CMakeCache.txt,
then the best is to not get such values into the cache, and thus use NEW
behavior.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

cmake: set the policy CMP0077 to NEW

---

lib/system/nuttx/time.c

follow up the change from NuttX side:
https://github.com/apache/incubator-nuttx/pull/1022

system: nuttx: change clock_systimespec to clock_systime_timespec

---

lib/system/zephyr/time.c

_sys_clock_tick_count has not existed for a number of zephyr releases
(last release was v1.13).  Use k_uptime_ticks() instead to implement
metal_get_timestamp.

zephyr: Fix metal_get_timestamp implementation

---

lib/compiler/gcc/atomic.h

Compiling for Zephyr bails out on typeof. Use \_\_typeof\_\_
which is accepted by gcc regardless of the c language version.
Signed-off-by: Bobby Noelte <b0661n0e17e@gmail.com>

gcc: use __typeof__ instead of typeof in atomic.h

---

examples/system/freertos/zynqmp_r5/zynqmp_amp_demo/common.h
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/common.h
lib/compiler/gcc/compiler.h
lib/compiler/iar/compiler.h
lib/processor/aarch64/cpu.h
lib/processor/x86/cpu.h
lib/processor/x86_64/cpu.h
lib/system/freertos/zynq7/sys.c
lib/system/freertos/zynqmp_a53/sys.c
lib/system/freertos/zynqmp_r5/sys.c
lib/system/generic/microblaze_generic/sys.c
lib/system/generic/zynq7/sys.c
lib/system/generic/zynqmp_a53/sys.c
lib/system/generic/zynqmp_r5/sys.c
lib/system/zephyr/cortexm/sys.c
test/system/freertos/main.c

This patch makes a test file which includes all metal headers compile with the following arguments: -std=c11 -pedantic.
It is the reworked form of the draft pull request #125 
Tested with GCC 8.2.0.

Compatibility with pure C11 clients

---

lib/system/freertos/mutex.h
lib/system/generic/mutex.h

The` atomic_flag_*` functions are only defined for operands of the type `atomic_flag` [1] so the previous implementation relied on undefined behavior.
Because of the need for reading the status without side effects (in `__metal_mutex_is_acquired`), it is not possible to use the `atomic_flags` type for the mutex implementation. Because of this, this pull request replaces all  `atomic_flag_*` functions with the appropriate functions for atomic value types.
[1] e.g. see: https://en.cppreference.com/w/c/atomic/atomic_flag_test_and_set

Fix mutex implementation for FreeRTOS and Generic

---

lib/atomic.h
lib/io.h

This has been tried (81f85dc244d05448e26aa674301065a1220b4539) and reverted (23c3c332acd7e649033ba63d8905df7d59c1540c) before. This pull request is a bit more elaborate than the first try:
- When the headers are compiled as part of a C++ file, the functions and types from `<atomic>` are exported into the global namespace so that the inline functions still work (ba233adeeb0ed881ddf6c91cba7d35f27d1e5b46)
- A few more explicit typecasts are introduced where needed by the C++ implementation of `atomic_store_explicit` (195d46b46ff0ec825a5b4ce25e45fe1fea085665)
- Because the `atomic_flag_*` C++ functions also perform stricter type checking than the C ones, this depends on #126

Support C++ clients using <atomic>

---

lib/compiler/gcc/compiler.h
lib/compiler/iar/compiler.h

This PR is related to the issue https://github.com/OpenAMP/open-amp/issues/220
Define the __deprecated attribute to allow to generate a warning message
on compilation when an API is declared as deprecated.
This warning can be cleaned by adding -Wno-deprecated-declarations in
CMAKE_C_FLAGS flags

compiler: introduce __deprecated attribute

---

README.md
lib/system/freertos/sleep.h
lib/system/freertos/time.c
test/system/freertos/sleep.c

libmetal's libmetal_sleep_usec() takes a sleep time in micro-seconds.
The FreeRTOS function underlying it takes a sleep time in task ticks.
This was not properly corrected for, resulting in sleep times that
were off by an order of magnitude. The test code attempted to
correct for this as well, in the same wrong way.
Lastly, the metal_get_timestamp() function returned a value in
task ticks alone. This is a configuration dependent value.
This patch changes all three places to use microseconds for the
input and output values.
Addresses https://github.com/OpenAMP/libmetal/issues/117#

FreeRTOS: fix sleep and timestamp handling

---

.github/workflows/compliance.yml

When a PR is merged, a "Run failed: libmetal compliance checks - master"
mail is generated.
As it is not necessary to rerun this compliance check (already done
on sent PR), just suppress the action for push event.

CI: fix compliance check false report when merge a PR.

---

lib/system/linux/device.c

Hello,
It seems like metal_uio_read_map_attr() function is leaking a resource, please see valgrind output produced using a simple demo program that only open and close a device:
```
==2121== Memcheck, a memory error detector                                                                                                                                                                           
==2121== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.                                                                                                                                             
==2121== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info …
```

lib/system/linux: fix memory leak in metal_uio_read_map_attr()

---

README.md
lib/system/linux/device.c

I think there is a confusion about the of node "offset" of the uio map regions.
According to the user io documentation (https://www.kernel.org/doc/html/latest/driver-api/uio-howto.html), the offset node is 
> The offset, in bytes, that has to be added to the pointer returned by mmap()
this is NOT the offset to be passed to mmap.
The offset to give to mmap to get the Nth region is N times the pagesize as explained in the same documentation:
> From userspace, the different mappings are distinguished by adjusting the offset parameter of the mmap() call. To map the memory of mapping N, you have to use N times the page size as your offset:
```
offset = N * getpagesize();
```
The first patch https://github.com/OpenAMP/libmetal/pull/137/commits/2219961d1dc73d2f3e484f2701cf8fa18ebde1c7 of this …

Linux: fix misunderstanding of the offset devicetree node in the map

---

lib/system/freertos/sleep.h

metal_sleep_usec() used portTICK_PERIOD_MS to determine how long to
sleep. If the FreeRTOS tick rate is set to greater than 1000, this
will be 0, resulting in a divide by zero error at run time. This changes
it to use pdMS_TO_TICKS(), which can accomodate higher tick rates.
Signed-off-by: Ed Mooring <ed.mooring@linaro.org>

FreeRTOS: Allow tick rates greater than 1000 for metal_sleep_usec()

---

.github/actions/build_ci/entrypoint.sh

Update zephyr SDK to 0.12.4 to fix CI compatibility issue:

CI: fix Zephyr build by updating Zephyr SDK version

---

lib/system/zephyr/cache.h

Zephyr ships now a different API for cache management. Instead of
hijacking the call into Zephyr, use the proper API directly in libmetal.
Signed-off-by: Carlo Caione <ccaione@baylibre.com>

zephyr: cache: Use new Zephyr cache APIs

---

lib/io.c

metal_io_virt returns NULL on invalid input metal_io_region.
Check ptr before use it.
Signed-off-by: Mark-PK Tsai <mark-pk.tsai@mediatek.com>

io: add null pointer check in io block ops

---

.github/actions/build_ci/entrypoint.sh

Update zephyr SDK to 0.13 to fix CI compatibility issue.
The name of the steup file has also be updated.

CI: Fix Zephyr build by updating Zephyr SDK version to 13.0

---

lib/io.h
lib/system/nuttx/io.c

leads to ASAN errors
libmetal/lib/system/nuttx/io.c:78:9: runtime error: applying non-zero offset 4124131344 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131440 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131440 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131440 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131552 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124132000 to null pointer
==15484==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xffd3c000; bottom 0xf3437000; size: 0x0c905000 (210784256)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189

openamp/libmetal: fix Non-zero offsets to null pointers

---

.github/actions/build_ci/entrypoint.sh

CMake 3.20.0 or higher is required by Zephyr.
Use pip3 as recommended by zephyr project to get the last version.

CI: Fix Zephyr build error due to cmake version

---

lib/processor/xtensa/CMakeLists.txt
lib/processor/xtensa/atomic.h
lib/processor/xtensa/cpu.h

-libmetal: add xtensa support
-libmetal: add __sync_synchronize support

Port xtensa arch

---

lib/system/nuttx/io.c

```
libmetal/lib/system/nuttx/io.c: In function ‘metal_io_offset_to_phys_’:
libmetal/lib/system/nuttx/io.c:78:49: warning: passing argument 1 of ‘up_addrenv_va_to_pa’ makes pointer from integer without a cast [-Wint-conversion]
78 |  return up_addrenv_va_to_pa((uintptr_t)io->virt + offset);
|                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
|                                                 |
|                                                 long unsigned int
In file included from /home/ligd/platform/miwear/ap/nuttx/include/metal/system/nuttx/cache.h:19,
from /home/ligd/platform/miwear/ap/nuttx/include/metal/cache.h:15,
from libmetal/lib/system/nuttx/io.c:7:
/home/ligd/platform/miwear/ap/nuttx/include/nuttx/arch.h:1319:41: note: expected ‘void *’ but argument is of type ‘long …
```

libmeatal: fix warning

---

.github/workflows/compliance.yml
.github/workflows/continuous-integration.yml

See #183 for the underlying issue. 
Signed-off-by: Ed Mooring <ed.mooring@gmail.com>

CI: Use 'main' branch instead of 'master'.

---

lib/alloc.h
lib/condition.h
lib/dma.h
lib/io.h
lib/irq.h
lib/mutex.h
lib/softirq.h
lib/time.h

The header files including must be outside of the extern "C" { statement.
To be able to be included from C++ code.
Else such error can occur (reproduce on STM32MP1Cube distribution)
gcc/arm-none-eabi/include/c++/10.2.1/atomic:1467:3: error: template with C linkage
1467 |   template<typename _ITp>
|   ^~~~~~~~
In file included from STM32CubeMP1/Middlewares/Third_Party/OpenAMP/open-amp/lib/include/openamp/rpmsg.h:16,
from STM32CubeMP1/Middlewares/Third_Party/OpenAMP/open-amp/lib/include/openamp/open_amp.h:11,
from empty_main.cpp:1:
STM32CubeMP1/Middlewares/Third_Party/OpenAMP/libmetal/lib/include/metal/mutex.h:16:1: note: 'extern "C"' linkage
started here
16 | extern "C" {
| ^~~~~~~~~~

lib: fix compilation error with gcc++

---

cmake/syscheck.cmake
lib/system/zephyr/riscv/CMakeLists.txt
lib/system/zephyr/riscv/sys.c
lib/system/zephyr/riscv/sys.h

Make libmetal usable also for RISCV targets.
Signed-off-by: Carlo Caione <ccaione@baylibre.com>

zephyr: Enable support for RISCV

---

.github/actions/build_ci/entrypoint.sh
cmake/syscheck.cmake
lib/system/zephyr/xtensa/CMakeLists.txt
lib/system/zephyr/xtensa/sys.c
lib/system/zephyr/xtensa/sys.h

Make libmetal usable also for Xtensa targets.
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>

zephyr: Enable support for Xtensa

---

.github/actions/build_ci/entrypoint.sh

Add CI build test for the RISCV32 and RISCV64 architecture.

CI: add Zephyr build test for RISCV architecture

---

lib/system/freertos/io.c

Fix EWARM compilation error due to void pointer usage.
This fix has already been implemented for the generic system, but
was missing for the FreeRTOS.

freertos: io: fix IAR compile error due to 'void *' variable

---

lib/system/zephyr/sleep.h

The currently missing implementation causes invalid timeouts when sending
remoteproc messages over virtIO. With this change, the specified timeout
of 15 seconds can be achieved. This seems to be the only usage in Zephyr.
Signed-off-by: Matthias Fend <matthias.fend@emfend.at>

lib: system: zephyr: implement __metal_sleep_usec

---

.github/workflows/compliance.yml
scripts/checkpatch.pl
scripts/ci/check_compliance.py

The checkpatch.pl allows to run codespell on patches to highlight typo error.
Rebase the CI and checkpatch script on recent version and enable "codespell" tool

CI: enable codespell check 

---

lib/system/freertos/sleep.h
lib/system/generic/sleep.h
lib/system/linux/sleep.h
lib/system/nuttx/sleep.h
lib/system/zephyr/sleep.h

Fix "unbalanced grouping commands" warnings by cleaning up
the end-of-block occurrences, defined without starting tag.
No need to define an API interface block in these files, the
interface is already described in the main sleep.h file.

Doc: fix doc generation warnings in system sleep.h files

---

.checkpatch.conf

The 80 character limit is a warning which sometime affect the readability.
let's relax this limit to 100 as done in some other projects

checkpatch: Increase the default limit to 100 characters

---

lib/system/freertos/zynqmp_r5/sys.c
lib/system/generic/zynqmp_r5/sys.c

The metal_machine_io_mem_map() used to call Xil_SetMPURegion directly
and could get into an infinite loop. Replace the faulty code in
metal_machine_io_mem_map() with Xil_MemMap() call and assert it succeeds.
Signed-off-by: Sergei Korneichuk <sergei.korneichuk@amd.com>
---
fixes: 51e08c67556474762257a825fc92cf8dbd302388

zynqmp_r5: replace Xil_SetMPURegion with Xil_MemMap

---

lib/list.h

metal_list_find_node is used to ensure a node is not on a list before adding it
Signed-off-by: Tammy Leino <tammy_leino@mentor.com>

New routine to find a node on a list

---

lib/system/zephyr/cache.h

Use the new cache API for the cache hooks.
Signed-off-by: Carlo Caione <ccaione@baylibre.com>

zephyr: cache: Use new cache API

---

LICENSE.md

Update LICENSE.md with full and SPDX identifier details.
Note: Neither Apache nor GPL are used by the libmetal library itself.
Signed-off-by: Manikanta Sreeram <manikanta.sreeram@xilinx.com>

Update LICENSE.md to cover CI test scripts

---

examples/system/freertos/zynqmp_r5/zynqmp_amp_demo/ipi_latency_demod.c
examples/system/freertos/zynqmp_r5/zynqmp_amp_demo/ipi_shmem_demod.c
examples/system/freertos/zynqmp_r5/zynqmp_amp_demo/shmem_atomic_demod.c
examples/system/freertos/zynqmp_r5/zynqmp_amp_demo/shmem_latency_demod.c
examples/system/freertos/zynqmp_r5/zynqmp_amp_demo/shmem_throughput_demod.c
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/common.h
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/ipi_latency_demod.c
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/ipi_shmem_demod.c
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/shmem_atomic_demod.c
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/shmem_latency_demod.c
examples/system/generic/zynqmp_r5/zynqmp_amp_demo/shmem_throughput_demod.c
examples/system/linux/zynqmp/zynqmp_amp_demo/common.h
examples/system/linux/zynqmp/zynqmp_amp_demo/ipi_latency_demo.c
examples/system/linux/zynqmp/zynqmp_amp_demo/ipi_shmem_demo.c
examples/system/linux/zynqmp/zynqmp_amp_demo/shmem_atomic_demo.c
examples/system/linux/zynqmp/zynqmp_amp_demo/shmem_latency_demo.c
examples/system/linux/zynqmp/zynqmp_amp_demo/shmem_throughput_demo.c

Use atomic_flag type and the GCC __sync built-in
functions for atomic memory access.
Signed-off-by: Sergei Korneichuk <sergei.korneichuk@amd.com>

examples: use atomic_flag type, __sync functions

---

cmake/options.cmake

Fix PROJECT_EC_FLAGS definition: use set_property instead of set.
Signed-off-by: Sergei Korneichuk <sergei.korneichuk@amd.com>
--
This PR fixes an error in [cmake: set PROJECT_EC_FLAGS to be GLOBAL property](https://github.com/OpenAMP/libmetal/commit/d077e286a43784e517477e65071f1be15308f504)

cmake: use set_property for PROJECT_EC_FLAGS

---

README.md

Fix broken link that gives "page not found".
Signed-off-by: Hiago De Franco hiagofranco@gmail.com

readme: Fix broken openamp-rp mailing list link

---

lib/system/freertos/mutex.h

The `METAL_MUTEX_INIT` macro has been deprecated in release 2021.04.0
Remove it after it has been in a depreciated state for 2 years.

lib: system: freertos: remove deprecated METAL_MUTEX_INIT

---

scripts/checkpatch.pl

Fix issue https://github.com/OpenAMP/open-amp/issues/483
A false positive is "doesn't".  Occurrence of the word causes checkpatch
to emit the following warning:
"WARNING: 'doesn'' may be misspelled - perhaps 'doesn't'?"
The PR is a cherry pick of from Linux kernel:
https://lore.kernel.org/all/20201201190729.169733-1-dwaipayanray1@gmail.com/T/#u

checkpatch: fix TYPO_SPELLING check for words with apostrophe

---

lib/init.c
lib/sys.h

to allow to invoke metal_init and metal_finish multiple times

Add reference count to metal_common_state

---

lib/alloc.h
lib/system/freertos/alloc.h
lib/system/generic/alloc.h
lib/system/linux/alloc.h
lib/system/nuttx/alloc.h
lib/system/zephyr/alloc.h

This should have no functional change, but makes this header consistent with how the other headers are organized.

lib: refactor alloc.h to not need forward declaration

---

lib/atomic.h

The lib/atomic.h exports memory_order enum into the global namespace, but none of its enumerators. According to Section 7.3.3 "The using declaration" of the C++ standard: "specifying an enumeration name in a using-declaration does not declare its enumerators in the using-declaration's declarative region." See also: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0943r1.html

Export each of the memory_order enumerators

---

lib/system/freertos/sys.h

As lib/system/generic/sys.h has metal/errno.h add this to the freertos equivalent.
This fixes some compilation issues when linking against certain FreeRTOS port BSPs.

lib: system: freertos: Add metal/errno.h to match standalone

---

lib/utilities.h

If MB and GB definition is not available then define new ones.
This also addresses: https://github.com/OpenAMP/libmetal/pull/242

lib: utilities: add MB and GB defines

---

MAINTAINERS.md
README.md

Just some suggestions for minor text improvements I have after going through the libmetal docs.
Cheers,
Gustavo

Some suggestions for minor text improvements in the docs

---

.readthedocs.yaml
doc/CMakeLists.txt

The Readthedocs pull-request integration is nice to have for PR review. Run the whole OpenAMP-docs build but use the PR's commit
This also requires a ReadTheDocs project to install its integration for this repo. The project should enable "Build pull request for this project". It is currently in the Advanced Settings panel.
The project will also run for the main branch but that should be ignored and only the main project URL should be shown outside of PRs.
To this end the sub-module project names will use "-prs" in the name.

Docs: enable readthedocs rendering (for PRs)

---

.readthedocs.yaml

The original procedure worked only when the PR was coming from the same repo that was the target of the PR.  This is not normally the case.
The original check out has the commit we need.  Just use it as the remote, fetch and checkout the commit hash we need.

Docs: fix for the readthedocs PR rendering

---

README.md

The content from the wiki has been moved to the Sphinx based OpenAMP-docs. (Meeting notes will continue to be in the wiki only.)
The wiki data is probably out of date and will get more out of date as we go.
So point people to the official docs.
(Separately we plan to delete the non-meeting note wiki pages.)

README: Point people to the offical docs not the wiki

---

cmake/options.cmake
lib/CMakeLists.txt
lib/log.h

See also https://github.com/OpenAMP/libmetal/pull/250
Add "function-name:line-number" prefix and a new-line suffix for all messages. Use do-while(0) to define the metal_log macro. Add convenience macros ML_ERR, ML_WRN, ML_INF, ML_DBG to avoid using excessively long and redundant "metal_log(METAL_LOG_*".
I had to change s/irq/IRQ/ to fix the checkpatch warning: 
`EMBEDDED_FUNCTION_NAME: Prefer using '"%s...", __func__' to using 'irq', this function's name, in a string`

log: add function name, line number prefix

---

test/system/zephyr/main.c

In Zephyr PR #63351 , commit:
a35e40f410750f3205f0d87489aa0dfa4006e1d3
Support for k_mem_block was removed which was used by this Zephyr test.
Update the tets to just use a void* (which is what should be used instead).
----
Note this is the cause for the current CI failures.

Fix Zephyr testcase with latest Zephyr

---

.github/actions/build_ci/entrypoint.sh

A few minor changes to the CI script to reduce considerably the log size and do a minor speed up.
There are 3 main changes:
* wget prints less as it progresses (one dot per megabyte instead of KB) (~10K lines saved)
* The zephyr SDK extraction, instead of printing one line per file (~50K lines), it prints a progress bar updated every 3 seconds.
* west does a narrow update instead of a full update (only fetching the needed branch for each repo)

Minor improvements in entrypoint CI script

---

.github/workflows/stales.yml

By default the action closes the PR or issue 7 days after adding the stale label.
The expected behavior is that the pull requests and issues will never be closed automatically by the bot.

github action: Fix stales action to not close PR/issue after 7 days

---

.github/actions/build_ci/entrypoint.sh

To avoid having any misalignment between Zephyr and the SDK during CI tests, consider getting the latest version of the Zephyr SDK automatically instead of hardcoding it.
This approach should ensure that the latest version of sdk is always used.

CI: Zephyr: Get latest version of the zephyr sdk

---

lib/utilities.h

CPU0                                CPU1
create_ept1:addr1                   create_ept1
OK                       <======    msg1
OK                       <======    msg2
OK                       <======    msg3
msg4
<======    msg4 on the virtioqueue
close_ept1                          close_ept1
create_ept2:addr1                   create_ept1
(same addr with ept1)
msg4
ept2 recv ept1 msg ERROR <======
This should compile with https://github.com/OpenAMP/open-amp/pull/514

libmetal: set ept address loop++ in bitmap

---

lib/atomic.h
lib/compiler.h
lib/errno.h

The predefined macro __CC_ARM available on 5.x is migrated to the macro __arm__ for the version 6.x. Add defines to support both versions.
See https://developer.arm.com/documentation/ka005069/1-0/?lang=en for details

lib: compiler support of arm compiler v6

---

lib/compiler/armcc/errno.h

The new guards prevent redefinition of errno values which have already been defined in the standard libraries.

lib: add guards for errno values for ARMCC compiler

---

lib/system/zephyr/sys.c

arch_cpu_idle() is an internal API that should not be used outside of the main Zephyr. Use k_cpu_idle() instead, which is the same thing (at least for now).

zephyr: use k_cpu_idle instead of arch_cpu_idle

---

lib/system/zephyr/alloc.c
lib/system/zephyr/alloc.h

This define should be used instead of the Kconfig option to determine if the k_malloc family of functions are available.

Zephyr integration: Use K_HEAP_MEM_POOL_SIZE

---

lib/system/generic/xlnx/CMakeLists.txt
lib/system/generic/xlnx/sys.h
lib/system/generic/xlnx/sys_devicetree.h

This patch enables library and demo builds using latest Xilinx-AMD System Device (SDT) Flow update.

Latest Xilinx-AMD System Device Tree flow update

---

lib/system/generic/xlnx/sys.c

Avoiding memory mapping in MPU config table for region that are already mapped by bsp and no change in attribute property.

lib: xlnx: Avoid mapping in MPU for region mapped by bsp

---

lib/system/freertos/xlnx/sys.c

FreeRTOS patch for Avoiding memory mapping in MPU config table for region that are already mapped by bsp and no change in attribute property

FreeRTOS Avoid mem mapping in MPU for region mapped

---

lib/system/nuttx/io.c

libmetal/nuttx/io.c: width matched access when read/write size = 1,2,4,8
Follow the virtio spec v1.2
> 4.2.2.2 Driver Requirements: MMIO Device Register Layout:
The driver MUST only use 32 bit wide and aligned reads and writes to access the control registers described in table 4.1. For the device-specific configuration space, the driver MUST use 8 bit wide accesses for 8 bit wide fields, 16 bit wide and aligned accesses for 16 bit wide fields and 32 bit wide and aligned accesses for 32 and 64 bit wide fields.
So change the nuttx implemented io read/write operation.

libmetal/nuttx/io.c: width matched access when read/write size = 1,2,4,8

---

lib/system/freertos/xlnx/sys.c
lib/system/generic/xlnx/sys.c

Check if valid MPU flag is set or not. Current condition checks if flag is 0 or not, which is not intended use of flags

lib: system: MPU flag check fix for xilinx platform

---

test/metal-test.h

Small change to solve the warning: function declaration isn't a prototype when compiling tests with the GCC option -Wstrict-prototypes enabled.

test/metal-test.h: Fix warning -Wstrict-prototypes

---

.github/actions/build_ci/Dockerfile
.github/actions/build_ci/entrypoint.sh

The build check fails with following errors:
1) ln: failed to create symbolic link '/etc/localtime': File exists
Fix it by removing the link creation
2) error: externally-managed-environment
Fix it by adding "--break-system-packages" option to pip3

CI: fix timezone and pip3 issues

---

lib/device.h
lib/log.h
lib/shmem.h
lib/sys.h
lib/system/freertos/cache.h
lib/system/generic/cache.h
lib/system/linux/sys.h
lib/version.h

This is not needed for function declarations, they already have implicit external linkage.

lib: Do not label function declarations in headers with extern

---

lib/log.h

fix following warning:
lib/log.h:91: warning: argument 'args...' of command @param is not found in the argumentlist of metal_log(level, fmt, args...) lib/log.h:98: warning: The following parameter of
metal_log(level, fmt, args...) is not documented:
parameter 'args...'

lib: fix doxygen warning in log.h

---

lib/softirq.c

This message should state that there are no more available Soft IRQs.

lib: Fix available error message in softirq

---

.github/actions/build_ci/entrypoint.sh

The current CI uses the latest from main for zephyr build tests. This has been broken sometime after v3.6 and before v3.7 In Zephyr v3.7 and later, use of GNU style constructors requires a kconfig value to be defined.  This same kconfig value will cause an error in v3.6 or earlier.
The test framework intentionally uses GNU constructors for the base level of its framework and version.c uses this to register its test.
The test/system/zephyr/ level overrides the default META_ADD_TEST() macro and creates unique functions that main.c then calls explicitly in function metal_test_add_functions().
Thus, right now the only constructor used is for version.c but it still intentionally used.
Since we use the latest for CI, define the value so CI will complete.
Fixes: #304

CI: fix zephyr build for v3.7 and later

---

.github/actions/build_ci/entrypoint.sh
.github/workflows/continuous-integration.yml
.github/workflows/heathcheck.yml

Allow Zephyr testing to either use locked known good values or the very latest versions.
The known good versions are best for PR checking as if the build fails it is almost always the PR itself that broke it.
The latest version is good for periodically checking compatibility with the very latest Zephyr changes.
For now we run both on pushes and PRs.
We also run main against the latest zephyr check weekly as a look ahead.
Fixes: #295

CI: Do Zephyr build tests on known good and latest versions

---

README.md
cmake/platforms/zynq7-freertos.cmake
cmake/platforms/zynq7-generic-iar.cmake
cmake/platforms/zynq7-generic.cmake
cmake/platforms/zynq7-linux.cmake

Remove support for Zynq-7000 SoC, changes are
1. Remove Zynq7 tool chain support
2. Makefile changes to remove zynq7
Reasons to remove:
1. Support for Zynq-7000 has ended
2. Removing redundant or unmaintained code
3. Reduce technical debt carried by OpenAMP team
4. very few customer using openamp on Zynq-7000 SoC
For using Zynq-7000 SoC support last working and tested version is (v2023.10)
https://github.com/OpenAMP/libmetal/tree/v2023.10

zynq: Remove support for Zynq-7000 SoC

---

lib/system/nuttx/io.c

Because nuttx/io.c use NULL and NULL is defined in <stddef.h>

lib/system/nuttx/io.c: include <stddef.h> in nuttx/io.c

---

lib/system/nuttx/device.c
lib/system/nuttx/init.c
lib/system/nuttx/io.c
lib/system/nuttx/io.h

fix compile error:
/home/wyr/work/code/project/cardev/nuttx/openamp/libmetal/lib/system/nuttx/device.c:16:22: error: 'io' undeclared (first use in this function)
16 |         metal_unused(io);
/home/wyr/work/code/project/cardev/nuttx/openamp/libmetal/lib/system/nuttx/device.c:14:53: error: unused parameter 'dev' [-Werror=unused-parameter]
14 | int metal_generic_dev_sys_open(struct metal_device *dev)
...

lib/system/nuttx: fix undeclared parameter compile error

---

lib/system/freertos/sys.h
lib/system/freertos/template/sys.h
lib/system/freertos/xlnx/sys.h
lib/system/linux/sys.h
lib/system/nuttx/sys.h
lib/system/zephyr/sys.h

metal_yield would be managed at the OS level and dispatched to metal_cpu_yield, metal_sleep_usec, or others, it is more flexible to manage this in libmetal

lib/cpu.h: create a new libmetal API metal_yield

---

cmake/depends.cmake

there is no need to use cmake include detection under NuttX platform

libmetal(cmake): set HAVE_STDATOMIC_H default true in NuttX platform

---

lib/system/generic/sys.h

The metal_yield API needs also to be declared for the baremetal systems. This fix build issue in Open-amp for generic system:
/github/workspace/open-amp/lib/rpmsg/rpmsg_virtio.c:275:17: error: implicit declaration of function 'metal_yield'
275 |                 metal_yield();
|                 ^~~~~~~~~~~

lib: system: fix missing metal_yield API for generic systems.

---

lib/atomic.h
lib/compiler.h
lib/errno.h

lib/errno.h: defined(__ARMCC_VERSION) for use GCC compile
lib/autmoic:fix compiler error:
nuttx/include/metal/compiler/gcc/atomic.h:19:13: error: conflicting type qualifiers for 'atomic_flag'
19 | typedef int atomic_flag;
| ^~~~~~~~~~~
In file included from nuttx/include/nuttx/net/netdev_lowerhalf.h:38,
from virtio/virtio-net.c:33:
prebuilts/gcc/linux/arm/lib/gcc/arm-none-eabi/13.2.1/include/
stdatomic.h:233:3: note: previous declaration of 'atomic_flag' with
type 'atomic_flag'
233 | } atomic_flag;
| ^~~~~~~~~~~
nuttx/include/metal/compiler/gcc/atomic.h:20:14: error: conflicting
type qualifiers for 'atomic_char'
20 | typedef char atomic_char;
^~~~~~~~~~~

lib: fix compile error

---

lib/processor/CMakeLists.txt
lib/processor/hosted/cpu.c
lib/processor/hosted/cpu.h

Fix cross inclusion between metal/sys.h and /processor/hosted/cpu.h replacing metal_wait_usec by k_busy_wait function call.
Issue reported by Zephyr twister CI test: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11482800628/job/31962168738?pr=80324
libmetal/lib/include/metal/processor/hosted/cpu.h:19:9: error: implicit declaration of function ‘metal_wait_usec’
19 |         metal_wait_usec(10);
|         ^~~~~~~~~~~~~~~
libmetal/lib/include/metal/system/zephyr/sys.h:46:20:
error: conflicting types for ‘metal_wait_usec’; have ‘void(uint32_t)’
46 | static inline void metal_wait_usec(uint32_t usec_to_wait)
|                    ^~~~~~~~~~~~~~~
libmetal/lib/include/metal/processor/hosted/cpu.h:19:9:
note: previous implicit declaration of ‘metal_wait_usec’ with
type ‘void(uint32_t)’ …

lib: processor: hosted: fix compilation warning in metal_cpu_yield

---

lib/system/nuttx/mutex.h

Now nuttx use NXMUTEX_INITIALIZER to initialize the mutex, so updated.

nuttx/mutex.h: bug fix, change MUTEX_INITIALIZER to NXMUTEX_INITIALIZER

---

lib/system/freertos/io.c
lib/system/generic/io.c

In metal_sys_io_mem_map() if the I/O region size
is a multiple of (1<<page_shift) will result in a
buffer overflow in the for loop.
Therefore, adjust loop termination condition to
prevent accessing an out-of-bounds page.

io: fix buffer overflow in metal_sys_io_mem_map()

---

.readthedocs.yaml
doc/readthedocs-conf.py

Upstream Read The Docs has tightened up the schema checking and this broke what we were doing for PRs.
A good number of things were tried but the best compromise is to:
* supply a dummy sphinx config file in this repo
* override the default build command to use the openamp-docs dir
Also:
* add more documentation about what is going on
* lock to html only format.  PRs only do html anyway but make sure

docs: update the readthedocs integration for PRs in this repo

---

CMakeLists.txt

We currently support an old version of CMake (3.0.2) that was released in 2018.
This requires adding specific policies to support the evolution to the latest versions of Zephyr.
Update the minimum version to 3.16. The reason for this version is to support environments such as Debian Bullseye that are still in LTS state.
By updating to CMake 3.16 as the minimum version, we can also clean up the following policy add-ons:
- CMP0048 added in CMake v3.0
- CMP0053 added in CMake v3.1
- CMP0077 added in CMake v3.13

cmake: update cmake minimum support to 3.16

---

.github/actions/build_ci/entrypoint.sh

Bump to Zephyr 4.1 and SDK 0.17.

CI: Update zephyr known good versions

---

doc/Doxyfile.in

Not sure which branch/tag this pull request should be to, so adjust as required.
In order to be able to embed (through breathe) and link to (through doxylink) doxygen content in this repository through the RST (restructured text) files of https://github.com/OpenAMP/openamp-docs the doxygen generation needs to enable xml and tag file generation.
Once this pull request is in place, openamp-docs git submodule needs to be bumped to make the change effective for the document generation.

Doxygen: Generate tag and xml

---

test/system/linux/threads.c

Do not rely on indirect includes since they may not be present on some systems.

system: linux: include missing headers

---

lib/CMakeLists.txt

For consumers who don't want to install libmetal it's more convenient to use the CMake targets metal-static or metal-shared. However, they currently don't bring the necessary include directories (In contrast to the Zephyr version where the include directories are already exported via `zephyr_include_directories(...)`)

add public header files for to metal-shared/static CMake targets

---

lib/system/linux/device.c

As the code path suggests, the pointer, ldev, at this point, can be free'd directly w/o a check.  Remove the redundant check.

lib: system: linux: Remove redundant malloc'd addr release check
